# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dragonnest_pb2 as dragonnest__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dragonnest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/dragonnest.v1.BrainControl/Connect',
                request_serializer=dragonnest__pb2.DeviceToBrain.SerializeToString,
                response_deserializer=dragonnest__pb2.BrainToDevice.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/dragonnest.v1.BrainControl/SubmitTask',
                request_serializer=dragonnest__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=dragonnest__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/dragonnest.v1.BrainControl/GetTask',
                request_serializer=dragonnest__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=dragonnest__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)


class BrainControlServicer:
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=dragonnest__pb2.DeviceToBrain.FromString,
                    response_serializer=dragonnest__pb2.BrainToDevice.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=dragonnest__pb2.SubmitTaskRequest.FromString,
                    response_serializer=dragonnest__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=dragonnest__pb2.GetTaskRequest.FromString,
                    response_serializer=dragonnest__pb2.SubmitTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dragonnest.v1.BrainControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dragonnest.v1.BrainControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dragonnest.v1.BrainControl/Connect',
            dragonnest__pb2.DeviceToBrain.SerializeToString,
            dragonnest__pb2.BrainToDevice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dragonnest.v1.BrainControl/SubmitTask',
            dragonnest__pb2.SubmitTaskRequest.SerializeToString,
            dragonnest__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dragonnest.v1.BrainControl/GetTask',
            dragonnest__pb2.GetTaskRequest.SerializeToString,
            dragonnest__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
